export const pickupLines = [ 
    { question: "Are you a magician?", answer: "Because whenever I look at you, everyone else disappears." },
    { question: "Do you have a name?", answer: "Or can I call you mine?" },
    { question: "Do you believe in love at first sight?", answer: "Or should I walk by again?" },
    { question: "Are you French?", answer: "Because Eiffel for you." },
    { question: "Are you WiFi?", answer: "Because I'm really feeling a connection." },
    { question: "Can you lend me a kiss?", answer: "I promise I'll give it back." },
    { question: "Are you a time traveler?", answer: "Because I see you in my future." },
    { question: "Do you have a Band-Aid?", answer: "Because I just scraped my knee falling for you." },
    { question: "Are you a parking ticket?", answer: "Because you’ve got ‘FINE’ written all over you." },
    { question: "Are you an angel?", answer: "Because heaven is missing one." },
    { question: "Is your name Google?", answer: "Because you have everything I’ve been searching for." },
    { question: "Are you made of copper and tellurium?", answer: "Because you're Cu-Te." },
    { question: "Are you a campfire?", answer: "Because you’re hot and I want s’more." },
    { question: "Do you have a sunburn?", answer: "Or are you always this hot?" },
    { question: "If you were a vegetable, what would you be?", answer: "A cute-cumber." },
    { question: "Are you a keyboard?", answer: "Because you're just my type." },
    { question: "Do you have a pencil?", answer: "Because I want to erase your past and write our future." },
    { question: "Are you a beaver?", answer: "Because daaaaam." },
    { question: "What am I, a snowflake?", answer: "Because I've fallen for you." },
    { question: "You must be a high test score, why?", answer: "Because I want to take you home and show my mom." },
    { question: "Do you like Star Wars?", answer: "Because Yoda one for me." },
    { question: "Are you a bank loan?", answer: "Because you have my interest." },
    { question: "Are you a dictionary?", answer: "Because you add meaning to my life." },
    { question: "Are you an elevator?", answer: "Because you lift my spirits." },
    { question: "Is your name Netflix?", answer: "Because I could binge you all day." },
    { question: "Are you a volcano?", answer: "Because I lava you." },
    { question: "Are you Cinderella?", answer: "Because your shoe fits perfectly in my heart." },
    { question: "Are you a genie?", answer: "Because you just granted my wish." },
    { question: "Do you have a map?", answer: "Because I just got lost in your eyes." },
    { question: "Are you an astronaut?", answer: "Because your beauty is out of this world." },
    { question: "Are you a cloud?", answer: "Because you make my heart soar." },
    { question: "Are you a detective?", answer: "Because you just solved the mystery of my heart." },
    { question: "Are you a chef?", answer: "Because you just seasoned my heart with love." },
    { question: "Are you a shooting star?", answer: "Because I wished for someone like you." },
    { question: "Are you a marathon?", answer: "Because my heart races when I see you." },
    { question: "Are you a mirror?", answer: "Because I see myself in you." },
    { question: "Are you a dream?", answer: "Because I never want to wake up." },
    { question: "Are you a lighthouse?", answer: "Because you light up my darkest days." },
    { question: "Are you a book?", answer: "Because every chapter of you is worth reading." },
    { question: "Are you a melody?", answer: "Because my heart beats to your rhythm." },
    { question: "Are you the ocean?", answer: "Because I'm lost in your waves." },
    { question: "Are you a scientist?", answer: "Because I have a chemical reaction every time I see you." },
    { question: "Is your dad a baker?", answer: "Because you're a cutie pie." },
    { question: "Are you a battery?", answer: "Because you just gave me a charge." },
    { question: "Are you a firefighter?", answer: "Because you just set my heart on fire." },
    { question: "Are you from Tennessee?", answer: "Because you're the only ten I see." },
    { question: "Is your name Chapstick?", answer: "Because you're da balm." },
    { question: "Are you a sunrise?", answer: "Because you brighten up my mornings." },
    { question: "Are you a time machine?", answer: "Because I see a future with you." },
    { question: "Are you an equation?", answer: "Because you complete my formula for happiness." },
    { question: "Do you like tea?", answer: "Because you are excep-tea-onal." },
    { question: "Are you a rainbow?", answer: "Because you bring color into my life." },
    { question: "Are you an artist?", answer: "Because you just painted my heart with love." },
    { question: "Do you believe in fate?", answer: "Because I think we were meant to meet." },
    { question: "Are you a meteor?", answer: "Because you just made an impact on my heart." },
    { question: "Are you a butterfly?", answer: "Because every time I see you, my stomach flutters." },
    { question: "Do you have a quarter?", answer: "Because I want to call my mom and tell her I met the one." },
    { question: "Are you a camera?", answer: "Because every time I look at you, I smile." },
    { question: "Are you a skeleton?", answer: "Because you just made my heart race." },
    { question: "Are you a sunrise or a sunset?", answer: "Because either way, you make my world beautiful." },
    { question: "Are you a ferris wheel?", answer: "Because my heart goes up and down when I see you." },
    { question: "Are you a lock?", answer: "Because you've got the key to my heart." },
    { question: "Are you an architect?", answer: "Because you just built a bridge straight to my heart." },
    { question: "Are you a comet?", answer: "Because you light up my darkest nights." },
    { question: "Are you a gardener?", answer: "Because you've planted love in my heart." },
    { question: "Are you a map?", answer: "Because I’d be lost without you." },
    { question: "Are you a conductor?", answer: "Because every time you’re around, there’s electricity in the air." },
    { question: "Are you a math problem?", answer: "Because you’ve got me completely puzzled and interested." },
    { question: "Are you a constellation?", answer: "Because you brighten up my night sky." },
    { question: "Are you a cup of coffee?", answer: "Because you keep me awake thinking about you." },
    { question: "Are you a North Star?", answer: "Because no matter where I am, I always find my way to you." },
    { question: "Are you a compass?", answer: "Because I feel like I'm being pulled toward you." },
        { question: "Are you a magician?", answer: "Because whenever I look at you, everyone else disappears." },
        { question: "Do you have a name, or can I call you mine?", answer: "Because I'd love to call you mine." },
        { question: "Are you French?", answer: "Because Eiffel for you." },
        { question: "Do you have a map?", answer: "Because I keep getting lost in your eyes." },
        { question: "Are you a bank loan?", answer: "Because you have my interest!" },
        { question: "Is your name Google?", answer: "Because you have everything I've been searching for." },
        { question: "Are you a Wi-Fi signal?", answer: "Because I'm really feeling a connection." },
        { question: "Do you have a Band-Aid?", answer: "Because I just scraped my knee falling for you." },
        { question: "Are you an angel?", answer: "Because heaven is missing one." },
        { question: "Do you like Star Wars?", answer: "Because Yoda one for me." },
        { question: "Are you a parking ticket?", answer: "Because you've got 'FINE' written all over you." },
        { question: "Are you made of copper and tellurium?", answer: "Because you're Cu-Te." },
        { question: "Are you a campfire?", answer: "Because you’re hot and I want s’more." },
        { question: "Is your dad a boxer?", answer: "Because you're a knockout!" },
        { question: "Are you a time traveler?", answer: "Because I see you in my future." },
        { question: "Are you an electrician?", answer: "Because you’re lighting up my life." },
        { question: "Do you believe in fate?", answer: "Because it brought me to you." },
        { question: "Are you a snowstorm?", answer: "Because you just made my heart race." },
        { question: "Are we at the airport?", answer: "Because my heart is taking off whenever I see you." },
        { question: "Are you a keyboard?", answer: "Because you’re just my type." },
        { question: "Do you believe in love at first sight?", answer: "Or should I walk by again?" },
        { question: "Are you a camera?", answer: "Because every time I look at you, I smile." },
        { question: "Are you an alien?", answer: "Because you just abducted my heart." },
        { question: "Are you an artist?", answer: "Because you just painted a smile on my face." },
        { question: "Are you a battery?", answer: "Because you keep me energized." },
        { question: "Are you the sun?", answer: "Because you brighten up my day." },
        { question: "Are you a rainbow?", answer: "Because you bring color to my life." },
        { question: "Are you a clock?", answer: "Because every second I spend with you is priceless." },
        { question: "Are you gravity?", answer: "Because you’ve got me falling for you." },
        { question: "Are you an ocean?", answer: "Because I’m lost at sea in your eyes." },
        { question: "Are you a diamond?", answer: "Because you’re truly priceless." },
        { question: "Are you a cupcake?", answer: "Because you’re sweet and irresistible." },
        { question: "Are you chocolate?", answer: "Because you’re sweet and irresistible." },
        { question: "Are you a song?", answer: "Because every time I hear you, my heart sings." },
        { question: "Are you a shooting star?", answer: "Because you just made my dreams come true." },
        { question: "Are you an adventure?", answer: "Because I want to go on this journey with you." },
        { question: "Are you a candle?", answer: "Because you light up my world." },
        { question: "Are you a teddy bear?", answer: "Because I just want to hug you all day." },
        { question: "Are you a secret?", answer: "Because I want to keep you all to myself." },
        { question: "Are you my future?", answer: "Because I see us together forever." },
        { question: "Are you a melody?", answer: "Because you’re music to my ears." },
        { question: "Are you the moon?", answer: "Because you light up my darkest nights." },
        { question: "Are you a good book?", answer: "Because I can’t put you down." },
        { question: "Are you my phone charger?", answer: "Because you give me life." },
        { question: "Are you my diary?", answer: "Because I want to tell you everything." },
        { question: "Are you a bouquet of flowers?", answer: "Because you make my world bloom." },
        { question: "Are you my favorite song?", answer: "Because I could play you on repeat all day." },
        { question: "Are you a piece of art?", answer: "Because you’re priceless." },
        { question: "Are you a four-leaf clover?", answer: "Because you’re my lucky charm." },
        { question: "Are you my GPS?", answer: "Because you always lead me to happiness." },
        { question: "Are you an open book?", answer: "Because I want to read every page of you." },
        { question: "Is your heart a library book?", answer: "Because I'd like to check you out." },
        { question: "Are you a treasure?", answer: "Because I’ve been searching my whole life to find you." },
        { question: "Are you a secret ingredient?", answer: "Because you make everything better." },
        { question: "Are you a lightbulb?", answer: "Because you brighten up my day." },
        { question: "Are you a spark?", answer: "Because you set my heart on fire." },
        { question: "Are you a volcano?", answer: "Because you make my heart erupt." },
        { question: "Are you a dream?", answer: "Because you're too good to be true." },
        { question: "Are you a lighthouse?", answer: "Because you guide me home." },
        { question: "Is your smile a magnet?", answer: "Because I'm irresistibly drawn to it." },
        { question: "Are you a comet?", answer: "Because you light up my universe." },
        { question: "Are you a snowflake?", answer: "Because I've fallen for you." },
        { question: "Are you a firework?", answer: "Because you light up my life." },
        { question: "Do you have a sunburn, or are you always this hot?", answer: "Because you're smoking!" },
        { question: "Are you a baker?", answer: "Because you've got a nice set of buns." },
        { question: "Are you a star?", answer: "Because your beauty outshines them all." },
        { question: "Are you a painter?", answer: "Because you've added color to my world." },
        { question: "Are you a mathematician?", answer: "Because you add meaning to my life." },
        { question: "Are you a poet?", answer: "Because you rhyme with beautiful." },
        { question: "Are you an exam?", answer: "Because I want to ace you." },
        { question: "Are you a fruit?", answer: "Because you're a fineapple." },
        { question: "Are you a gardener?", answer: "Because I’d love to plant a kiss on you." },
        { question: "Are you a summer day?", answer: "Because you're hot and bright." },
        { question: "Are you a winter night?", answer: "Because you make my heart warm." },
        { question: "Are you a puzzle?", answer: "Because I just can't figure you out and I love it." },
        { question: "Are you a joke?", answer: "Because you always make me smile." },
        { question: "Are you a candy bar?", answer: "Because you're sweet and a little nutty." },
        { question: "Are you a sunrise?", answer: "Because you light up my morning." },
        { question: "Are you a sunset?", answer: "Because you take my breath away." },
        { question: "Are you a starfish?", answer: "Because I’m lost in your beauty." },
        { question: "Are you a magnet?", answer: "Because I'm attracted to you." },
        { question: "Are you a firecracker?", answer: "Because you make my heart go boom." },
        { question: "Are you a snow cone?", answer: "Because you’re cool and sweet." },
        { question: "Are you a poet's dream?", answer: "Because you inspire every line." },
        { question: "Are you an opera?", answer: "Because your beauty is timeless." },
        { question: "Are you a symphony?", answer: "Because your voice is music to my ears." },
        { question: "Are you a prism?", answer: "Because you break my world into beautiful colors." },
        { question: "Are you an elevator?", answer: "Because you lift me up." },
        { question: "Are you a door?", answer: "Because I want to open up to you." },
        { question: "Are you a window?", answer: "Because I see endless possibilities in you." },
        { question: "Are you a heartbeat?", answer: "Because mine races when you're near." },
        { question: "Are you a dream come true?", answer: "Because I never knew true happiness until I met you." },
        { question: "Are you a wonder?", answer: "Because you're simply amazing." },
        { question: "Are you a fire?", answer: "Because you ignite something in me." },
        { question: "Are you a blanket?", answer: "Because I feel warm around you." },
        { question: "Are you a movie?", answer: "Because I can't take my eyes off you." },
        { question: "Are you a novel?", answer: "Because your story is captivating." },
        { question: "Are you a poem?", answer: "Because every word you speak is beautiful." },
        { question: "Are you a mountain?", answer: "Because my love for you is as high as the peaks." },
        { question: "Are you a river?", answer: "Because I feel an endless flow of love for you." },
        { question: "Are you a flame?", answer: "Because you set my heart ablaze." },
        { question: "Are you a breeze?", answer: "Because you make my day refreshing." },
        { question: "Are you a book?", answer: "Because I could read you all night." },
        { question: "Are you a tweet?", answer: "Because you're trending in my heart." },
        { question: "Are you a song lyric?", answer: "Because you stick in my head." },
        { question: "Are you an artist's muse?", answer: "Because you inspire every masterpiece." },
        { question: "Are you a masterpiece?", answer: "Because I could stare at you forever." },
        { question: "Are you a chef?", answer: "Because you just cooked up a storm in my heart." },
        { question: "Are you a spark plug?", answer: "Because you ignite my engine." },
        { question: "Are you a smile?", answer: "Because you brighten my day." },
        { question: "Are you a secret?", answer: "Because I love discovering you." },
        { question: "Are you a sweet dream?", answer: "Because I never want to wake up." },
        { question: "Are you a wish?", answer: "Because my dreams start with you." },
        { question: "Are you a cloud?", answer: "Because you're floating through my mind all day." },
        { question: "Are you a star?", answer: "Because you light up my night." },
        { question: "Are you a spark?", answer: "Because you set off fireworks in my heart." },
        { question: "Are you a masterpiece in progress?", answer: "Because every day with you is art." },
        { question: "Are you a gardener?", answer: "Because you make my heart bloom." },
        { question: "Are you a melody in a quiet room?", answer: "Because your voice is soothing." },
        { question: "Are you a poem written in the stars?", answer: "Because your beauty is eternal." },
        { question: "Are you a cup of coffee?", answer: "Because you keep me awake at night." },
        { question: "Are you a moonbeam?", answer: "Because you light up my darkest moments." },
        { question: "Are you a wonderland?", answer: "Because being with you feels magical." },
        { question: "Are you a comet trail?", answer: "Because your glow follows you wherever you go." },
        { question: "Are you a garden?", answer: "Because you've planted love in my heart." },
        { question: "Are you a chef's secret recipe?", answer: "Because you're the perfect blend of sweet and spicy." },
        { question: "Are you a painting?", answer: "Because every stroke of you is art." },
        { question: "Are you a compass?", answer: "Because you direct me to my true north." },
        { question: "Are you a coin?", answer: "Because I feel lucky every time I'm with you." },
        { question: "Are you a star map?", answer: "Because I can find my way in your eyes." },
        { question: "Are you a melody that lingers?", answer: "Because your tune plays on in my heart." },
        { question: "Are you a spark in the dark?", answer: "Because you light up every corner of my soul." },
        { question: "Are you a whisper?", answer: "Because I can hear your heart calling me." },
        { question: "Are you a flame on a cold night?", answer: "Because you warm my heart." },
        { question: "Are you a fresh start?", answer: "Because every moment with you feels new." },
        { question: "Are you a journey?", answer: "Because I want to explore every path with you." },
        { question: "Are you a firework?", answer: "Because you make every moment spectacular." },
        { question: "Are you a gentle breeze?", answer: "Because you calm my restless heart." },
        { question: "Are you a midnight snack?", answer: "Because you're exactly what I've been craving." },
        { question: "Are you a magic trick?", answer: "Because you make all my troubles disappear." },
        { question: "Are you a light in the dark?", answer: "Because you make everything brighter." },
        { question: "Are you a sparkler?", answer: "Because you make celebrations even better." },
        { question: "Are you a dreamcatcher?", answer: "Because you caught my heart." },
        { question: "Are you a candlelight dinner?", answer: "Because you're the highlight of my evening." },
        { question: "Are you a starlit sky?", answer: "Because you leave me in awe." },
        { question: "Are you a constellation?", answer: "Because together, we create a masterpiece in the sky." },
        { question: "Are you a photograph?", answer: "Because every moment with you is picture-perfect." },
        { question: "Are you a sweet melody?", answer: "Because your voice resonates in my heart." },
        { question: "Are you a soothing song?", answer: "Because your presence is my favorite tune." },
        { question: "Are you a gentle rain?", answer: "Because you wash all my worries away." },
        { question: "Are you a lighthouse?", answer: "Because you guide me through life's storms." },
        { question: "Are you a treasure chest?", answer: "Because I found my gold in you." },
        { question: "Are you a warm hug?", answer: "Because I never want to let you go." },
        { question: "Are you a refreshing drink?", answer: "Because you quench my thirst for love." },
        { question: "Are you a secret garden?", answer: "Because every moment with you is enchanting." },
        { question: "Are you a rhythm?", answer: "Because my heart beats in sync with yours." },
        { question: "Are you a gentle whisper?", answer: "Because your words linger in my soul." },
        { question: "Are you a comforting blanket?", answer: "Because you keep me warm on cold days." },
        { question: "Are you a spark in my darkness?", answer: "Because you ignite hope in me." },
        { question: "Are you a dance?", answer: "Because every step with you is pure joy." },
        { question: "Are you a summer breeze?", answer: "Because you make everything feel lighter." },
        { question: "Are you a cool shade?", answer: "Because you make even the hottest days bearable." },
        { question: "Are you a refreshing wave?", answer: "Because you sweep me off my feet." },
        { question: "Are you a gentle stream?", answer: "Because you flow gracefully into my heart." },
        { question: "Are you a morning dew?", answer: "Because you make everything fresh." },
        { question: "Are you a field of flowers?", answer: "Because your beauty is naturally captivating." },
        { question: "Are you a hidden gem?", answer: "Because finding you was a lucky discovery." },
        { question: "Are you a treasure map?", answer: "Because you lead me to priceless moments." },
        { question: "Are you a ray of sunshine?", answer: "Because you brighten up my darkest days." },
        { question: "Are you a cup of tea?", answer: "Because you warm me from the inside out." },
        { question: "Are you a piece of music?", answer: "Because you set the rhythm of my heart." },
        { question: "Are you a gentle touch?", answer: "Because your caress leaves me breathless." },
        { question: "Are you a soft whisper?", answer: "Because your words echo in my heart." },
        { question: "Are you a clear sky?", answer: "Because you clear away all my clouds." },
        { question: "Are you a gentle snowfall?", answer: "Because you make the world a wonderland." },
        { question: "Are you a flickering candle?", answer: "Because you add warmth to every moment." },
        { question: "Are you a rare gem?", answer: "Because your beauty is one of a kind." },
        { question: "Are you a cherished memory?", answer: "Because I never want to forget you." },
        { question: "Are you a morning star?", answer: "Because you herald a new day of love." },
        { question: "Are you a midnight dream?", answer: "Because you're as enchanting as the night." },
        { question: "Are you a delicate flower?", answer: "Because you brighten the garden of my heart." },
        { question: "Are you a cool breeze?", answer: "Because you make even the warmest days feel refreshing." },
        { question: "Are you a shooting comet?", answer: "Because you leave a trail of magic behind." },
        { question: "Are you a playful kitten?", answer: "Because you bring joy into my life." },
        { question: "Are you a radiant smile?", answer: "Because your grin lights up the room." },
        { question: "Are you a gentle giant?", answer: "Because your presence makes me feel safe." },
        { question: "Are you a lucky charm?", answer: "Because I feel fortunate every time I see you." },
        { question: "Are you a crisp apple?", answer: "Because you're as sweet as can be." },
        { question: "Are you a cool mint?", answer: "Because you freshen up my world." },
        { question: "Are you a cozy sweater?", answer: "Because being with you feels so warm." },
        { question: "Are you a hidden treasure?", answer: "Because I feel rich every time I see you." },
        { question: "Are you a sparkling diamond?", answer: "Because your brilliance is unmatched." },
        { question: "Are you a gourmet meal?", answer: "Because you satisfy all my cravings." },
        { question: "Are you a deep ocean?", answer: "Because I could drown in your eyes." },
        { question: "Are you a soothing lullaby?", answer: "Because your voice calms my soul." },
        { question: "Are you a work of art?", answer: "Because every glance at you is a masterpiece." },
        { question: "Are you a warm fire?", answer: "Because you keep my heart glowing." },
        { question: "Are you a cool breeze on a hot day?", answer: "Because you refresh my soul." },
        { question: "Are you a gentle stream?", answer: "Because your love flows endlessly." },
        { question: "Are you a secret spell?", answer: "Because you've bewitched my heart." },
        { question: "Are you a fine wine?", answer: "Because you just get better with time." },
        { question: "Are you a classic song?", answer: "Because your melody never fades." },
        { question: "Are you a hidden melody?", answer: "Because you play softly on my heartstrings." },
        { question: "Are you a favorite book?", answer: "Because I could get lost in you for hours." },
        { question: "Are you a secret passage?", answer: "Because you lead me to hidden wonders." },
        { question: "Are you a spark in the night?", answer: "Because you illuminate my soul." },
        { question: "Are you a cool stream?", answer: "Because your flow is mesmerizing." },
        { question: "Are you a rare flower?", answer: "Because your beauty is one in a million." },
        { question: "Are you a gentle rain?", answer: "Because you wash away my worries." },
        { question: "Are you a candle in the dark?", answer: "Because your light is my guide." },
        { question: "Are you a silken scarf?", answer: "Because you wrap me in comfort." },
        { question: "Are you a blazing fire?", answer: "Because you warm my heart like no other." },
        { question: "Are you a whispering wind?", answer: "Because your voice is my favorite sound." },
        { question: "Are you a soft pillow?", answer: "Because I dream of you every night." },
        { question: "Are you a sweet treat?", answer: "Because your charm is absolutely delicious." },
        { question: "Are you a cherished song?", answer: "Because your lyrics echo in my heart." },
        { question: "Are you a radiant sunset?", answer: "Because you bring calm after the storm." },
        { question: "Are you a burst of laughter?", answer: "Because you brighten my darkest days." },
        { question: "Are you a gentle glow?", answer: "Because your presence warms my soul." },
        { question: "Are you a blooming rose?", answer: "Because your beauty is timeless." },
        { question: "Are you a playful breeze?", answer: "Because you make my heart flutter." },
        { question: "Are you a classic movie?", answer: "Because I can watch you over and over." },
        { question: "Are you a soft melody?", answer: "Because your tune is soothing." },
        { question: "Are you a secret garden?", answer: "Because I find peace in your eyes." },
        { question: "Are you a morning coffee?", answer: "Because you wake up all my senses." },
        { question: "Are you a cool shade?", answer: "Because you shelter me from the heat." },
        { question: "Are you a gentle snowfall?", answer: "Because you make everything beautiful." },
        { question: "Are you a flickering light?", answer: "Because you shine even in the darkness." },
        { question: "Are you a tender hug?", answer: "Because your embrace feels like home." },
        { question: "Are you a silent movie?", answer: "Because your expressions speak volumes." },
        { question: "Are you a timeless classic?", answer: "Because you never go out of style." },
        { question: "Are you a playful whisper?", answer: "Because your voice is music to me." },
        { question: "Are you a scenic view?", answer: "Because I could gaze at you forever." },
        { question: "Are you a secret admirer?", answer: "Because I've been enchanted by you." },
        { question: "Are you a gentle hum?", answer: "Because your rhythm resonates with me." },
        { question: "Are you a cool breeze on a summer night?", answer: "Because you refresh my soul." },
        { question: "Are you a spark in the cold?", answer: "Because you warm my heart." },
        { question: "Are you a symphony of stars?", answer: "Because your beauty orchestrates my dreams." },
        { question: "Are you a tender melody?", answer: "Because you play softly in my heart." },
        { question: "Are you a gentle whisper in the wind?", answer: "Because you carry my heart." },
        { question: "Are you a splash of color?", answer: "Because you brighten up my world." },
        { question: "Are you a midnight serenade?", answer: "Because your voice enchants me." },
        { question: "Are you a rare find?", answer: "Because meeting you is like discovering a hidden gem." },
        { question: "Are you a gentle stream of thought?", answer: "Because you flow gracefully in my mind." },
        { question: "Are you a warm ray of sunshine?", answer: "Because you brighten even the gloomiest day." },
        { question: "Are you a timeless beauty?", answer: "Because you never fade in my eyes." },
        { question: "Are you a gentle tide?", answer: "Because your love sweeps me away." },
        { question: "Are you a sweet whisper?", answer: "Because your words softly echo in my heart." },
        { question: "Are you a beautiful dream?", answer: "Because you make every moment magical." },
        { question: "Are you a playful wink?", answer: "Because your glance makes my heart skip a beat." },
        { question: "Are you a refreshing breeze?", answer: "Because you clear all my clouds away." },
        { question: "Are you a golden sunset?", answer: "Because you leave me speechless." },
        { question: "Are you a cool night?", answer: "Because your presence is wonderfully calming." },
        { question: "Are you a lively rhythm?", answer: "Because you set the pace of my heart." },
        { question: "Are you a comforting melody?", answer: "Because your tune lulls me to peace." },
        { question: "Are you a sparkling firefly?", answer: "Because you light up my evenings." },
        { question: "Are you a charming smile?", answer: "Because it's my favorite sight." },
        { question: "Are you a refreshing sip?", answer: "Because you quench my thirst for love." },
        { question: "Are you a gentle lullaby?", answer: "Because your voice soothes my soul." },
        { question: "Are you a secret hope?", answer: "Because you make me believe in miracles." },
        { question: "Are you a magical moment?", answer: "Because time stops when I'm with you." },
        { question: "Are you a captivating story?", answer: "Because I could listen to you for hours." },
        { question: "Are you a mysterious whisper?", answer: "Because you keep calling me back." },
        { question: "Are you a brilliant star?", answer: "Because you light up my universe." },
        { question: "Are you a playful dream?", answer: "Because you make my nights unforgettable." },
        { question: "Are you a soft melody of love?", answer: "Because your tune lingers in my heart." },
        { question: "Are you a bold adventure?", answer: "Because every moment with you is exciting." },
        { question: "Are you a dazzling firework?", answer: "Because you make every celebration brighter." },
        { question: "Are you a joyful laugh?", answer: "Because you bring happiness to my day." },
        { question: "Are you a precious gem?", answer: "Because your beauty is beyond measure." },
        { question: "Are you a gentle breeze in spring?", answer: "Because you refresh my spirit." },
        { question: "Are you a radiant glow?", answer: "Because your light is my guide." },
        { question: "Are you a sparkling gem?", answer: "Because you shine like no other." },
        { question: "Are you a breathtaking view?", answer: "Because every glance at you is mesmerizing." },
        { question: "Are you a vibrant painting?", answer: "Because your colors make life beautiful." },
        { question: "Are you a beautiful melody?", answer: "Because your song is my favorite." },
        { question: "Are you a warm embrace?", answer: "Because I feel at home with you." },
        { question: "Are you a brilliant idea?", answer: "Because you light up my thoughts." },
        { question: "Are you a tender moment?", answer: "Because I cherish every second with you." },
        { question: "Are you a captivating smile?", answer: "Because it steals my breath away." },
        { question: "Are you a charming soul?", answer: "Because your spirit inspires me." },
        { question: "Are you a serene landscape?", answer: "Because your beauty calms my mind." },
        { question: "Are you a burst of sunshine?", answer: "Because you brighten every corner of my day." },
        { question: "Are you a gentle rhythm?", answer: "Because your heartbeat is my favorite sound." },
        { question: "Are you a comforting embrace?", answer: "Because I feel safe in your arms." },
        { question: "Are you a sweet serenade?", answer: "Because your voice is music to my heart." },
        { question: "Are you a playful spirit?", answer: "Because every moment with you is fun." },
        { question: "Are you a wonderful surprise?", answer: "Because you make life exciting." },
        { question: "Are you a tender whisper of love?", answer: "Because you softly steal my heart." },
        { question: "Are you a dazzling smile?", answer: "Because your grin lights up my world." },
        { question: "Are you a perfect match?", answer: "Because we just click." },
        { question: "Are you a radiant bloom?", answer: "Because your beauty blossoms every day." },
        { question: "Are you a timeless treasure?", answer: "Because you’re priceless to me." },
        { question: "Are you a warm cup of cocoa?", answer: "Because you comfort me like no other." },
        { question: "Are you a cool night breeze?", answer: "Because you make my heart relax." },
        { question: "Are you a sweet melody in the dark?", answer: "Because your tune fills my soul." },
        { question: "Are you a shining star?", answer: "Because you guide me through the night." },
        { question: "Are you a gentle hug?", answer: "Because every embrace with you is magic." },
        { question: "Are you the love of my life?", answer: "Because with you, I've found my forever." }  
];
